config/routes.rb
Rails.application.routes.draw do

  resources :drivers, :only => [ :index, :show ]
  resources :laps, :only => [ :create ]
  resources :tracks, :only => [ :index, :show ]
  resources :screenshots, :only => [ :index, :show, :edit, :update ]
  resources :users, :except => [ :destroy ] do
    collection do
      get 'sign_in'
      get 'sign_out'
      get 'sign_up', :to => 'users#new'
      post 'do_sign_in'
      get 'reset_password'
      post 'send_reset_password'
    end
    member do
      get 'reset_password'
      post 'do_reset_password'
    end
    resources :sessions
    resources :drivers
  end

  resources :leagues, :only => [ :index, :show ]
  resources :seasons, :only => [ :show ]

  resources :races, :only => [ :index, :show ] do
    member do
      get 'livetiming'
    end
    collection do
      get 'without_sessions'
    end
  end

  resources :sessions do
    member do
      get 'chart'
    end
    collection do
      post 'register'
      get 'search'
    end
    resources :screenshots
  end

  namespace :say_what do
    resources :drivers, :super_leagues, :leagues, :seasons, :sessions, :laps, :screenshots, :tracks, :users
    resources :races do
      member do
        get 'rescan'
      end
    end
    get 'welcome', :to => 'welcome#index'
  end

  get 'help/aclog', :to => 'welcome#aclog'
  get 'help/rlcapp', :to => 'welcome#rlcapp'
  root :to => 'welcome#index'
end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  has_attached_file :image, :styles => { :three_quarters => "75%x75%>" }, :processors => [ :parse_image, :thumbnail ]
  process_in_background :image

  belongs_to :session, :counter_cache => true

  validate :laps_are_in_order, :on => :update, :if => lambda { |s| s.confirmed? }

  after_save :create_laps, :if => lambda { |s| s.confirmed? }

  def create_laps
    self.parsed.split(/\r\n/).each do |line|
      match = line.match(/^([\d]{2}) (([\d]+:)?[\d]{2}\.[\d]{3}) (([\d]+:)?[\d]{2}\.[\d]{3}) (([\d]+:)?[\d]{2}\.[\d]{3}) (([\d]+:)?[\d]{2}\.[\d]{3})/)

      lap = Lap.find_or_initialize_by(:session_id => session_id, :lap_number => match[1].to_i - 1)
      lap.total = Lap.convert_lap(match[2])
      lap.sector_1 = Lap.convert_lap(match[4])
      lap.sector_2 = Lap.convert_lap(match[6])
      lap.sector_3 = Lap.convert_lap(match[8])

      lap.save
    end
  end

  def laps_are_in_order
    input = parsed.scan(/^[\d]{2}/).map(&:to_i)
    expected = (input.first..input.last).to_a
    if input != expected
      errors[:base] << "The lap numbers are out of order or incorrect"
    end
  end

  def fia?
    self.session && self.session.race && self.session.race.fia?
  end
end

app/controllers/say_what/screenshots_controller.rb
class SayWhat::ScreenshotsController < ApplicationController
  before_filter :find_screenshot, :only => [ :show, :edit, :update, :destroy ]

  def index
    @screenshots = Screenshot.order(:created_at).page(params[:page].to_i).per(15)
  end

  def show
  end

  def new
    @screenshot = Screenshot.new
  end

  def edit
  end

  def create
    @screenshot = Screenshot.new(screenshot_params)
    @screenshot.save!
    respond_to do |format|
      format.js
      format.html { redirect_to(say_what_screenshots_path) }
    end
  rescue
    render('new')
  end

  def update
    @screenshot.update!(screenshot_params)
    redirect_to(say_what_screenshot_path(@screenshot), :notice => 'Screenshot was successfully updated.')
  rescue
    render "edit"
  end

  def destroy
    @screenshot.destroy
    redirect_to(say_what_screenshots_url, :notice => 'Screenshot deleted')
  end

  private

    def find_screenshot
      @screenshot = Screenshot.find(params[:id].to_i)
    end

    def screenshot_params
      params.require(:screenshot).permit(:image, :parsed, :session_id, :confirmed)
    end

end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_filter :find_screenshot, :only => [ :show, :edit, :update ]

  def index
  end

  def show
  end

  def edit
  end

  def update
    @screenshot.update!(screenshot_params)
    redirect_to(session_path(@screenshot.session), :notice => 'Screenshot was successfully updated.')
  rescue
    render "edit"
  end

  private

    def find_screenshot
      @screenshot = Screenshot.find(params[:id].to_i)
    end

    def screenshot_params
      params.require(:screenshot).permit(:confirmed, :parsed)
    end

end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
  def screenshot_popover_content(screenshot)
    if screenshot.session && screenshot.session.race && screenshot.session.race.fia?
      "Enter laps, lap times and sector times here. Syntax highlighting will help you with data entry - Black indicates a formatting problem. Red indicates a lap / sector time calculation error. Blue indicates that everything appears to be correct."
    else
      "This is the text that Tesseract returns from the screenshot. Black indicates a formatting problem. Red indicates a lap / sector time calculation error. Blue indicates that everything appears to be correct."
    end
  end
end

app/views/screenshots/_form.html.erb
<div>
  <div class="pull-left" style="margin-right: 10px">
    <div class="form-group">
      <%= f.label(:parsed, @screenshot.fia? ? "Lap Times" : "Parsed") %>
      <%= display_help(screenshot_popover_content(@screenshot)) %>
      <div style="border: solid 1px #000;">
      <%= f.text_area(:parsed, :class => 'form-control', :placeholder => 'Parsed Text') %>
      </div>
    </div>

    <div class="checkbox">
      <%= f.label(:confirmed) do %>
        <%= f.check_box(:confirmed, { :disabled => !@screenshot.fia? && (@screenshot.image.nil? || @screenshot.parsed.blank?) }) %> Lap times are correct?
      <% end %>
      <%= display_help('This lets the site know that you believe the lap times are correct and to generate individual lap records. There is no way to confirm the truth of this, please be honest :)') %>
    </div>

    <div class="form-group">
      <%= f.submit('Save', :class => 'btn btn-default') %> <%= cancel_link(@screenshot, false) %>
    </div>
  </div>

  <div class="pull-left" style="width:80%">
  <% unless @screenshot.fia? %>
    <p><strong>Image</strong></p>
    <%= image_tag(@screenshot.image.url(:three_quarters), :style => "width:100%") if @screenshot.image.exists? %>
  <% end %>
  </div>

</div>

app/views/screenshots/edit.html.erb
<h1>Edit <%= @screenshot.fia? ? "Lap Times" : "Screenshot" %></h1>
<%= form_for(@screenshot, :url => screenshot_path(@screenshot), :html => { :multipart => true }) do |f| %>
  <%= render(:partial => 'shared/errors', :object => @screenshot ) %>
  <%= render(:partial => 'form', :locals => { :f => f }) %>
<% end %>

app/views/screenshots/new.html.erb
<h1>New Screenshot</h1>
<%= form_for(@screenshot, :html => { :multipart => true }) do |f| %>
  <%= render(:partial => 'form', :locals => { :f => f }) %>
<% end %>